JeffLIrion/python-androidtv

androidtv/__init__.py

As per the official docs (https://developers.home-assistant.io/docs/en/integration_quality_scale_index.html#silver), "Handles device/service unavailable. Log a warning once when unavailable, log once when reconnected."
So I modified the connect funcion to only warn about an error if it has not been logged before.
Also, even if the device is unavailable, the logs would be filled with 'Update taking longer than 10s' every updates, to prevent that I added a timeout to ADB's connect function, and now everything is working as expected and the logs are not flooded. Also without this timeout, it would cause a delay of ~20s while launching HA.

Better handling of 'unavailable' property

---

androidtv/__init__.py

As the connect() function is executed before setting the self._available boolean, it needs to be set if the connection is successful, otherwise it's impossible.

python-adb initial connection is impossible

---

androidtv/__init__.py

As a user on the forum indicated, the output of adb shell getprop is not the same on different Android TV devices. Indeed on the Shield there is no wifi or bluetooth mac address.
I implemented a new way to fetch the Wifi mac if it's not present in the getprop output, and also removed the bluetooth mac as it's actually not needed.
EDIT: for some reason `wifi_out = self._adb_shell('ip addr show wlan0')` throws an error with `python-adb`, will investigate this.
EDIT2: seems that it's caused by sending ADB commands too quickly and crashing the connection.

Improve the device_info function

---

docs/source/adb_setup.rst

Reference: https://github.com/home-assistant/home-assistant/issues/22485#issuecomment-477891536
How does this look? I tried to keep it as generic as possible so it would work with any image. I also credited the script, and modified it to work with `sh` envs. As I had to do that to get it working in my env.

Add generic information on Docker

---

androidtv/androidtv.py
androidtv/basetv.py
androidtv/constants.py
androidtv/firetv.py
tests/test_androidtv.py
tests/test_firetv.py

* Improve the command for getting the current app so that it becomes a one-liner with no post-processing needed
* Use the current app to get the correct media session state
* Add state detection for Plex to `AndroidTV`

Improved current app and media session state

---

androidtv/androidtv.py
androidtv/basetv.py
androidtv/constants.py

During VRV playback, two audio states are available:
Partial output of `dumpsys_media` while VRV is open and paused:
```
ID:23 -- type:android.media.SoundPool -- u/pid:10031/3848 -- state:idle -- attr:AudioAttributes: usage=13 content=4 flags=0x0 tags= bundle=null
ID:327 -- type:OpenSL ES AudioPlayer (Buffer Queue) -- u/pid:10107/31690 -- state:started -- attr:AudioAttributes: usage=1 content=0 flags=0x0 tags= bundle=null
ID:343 -- type:android.media.AudioTrack -- u/pid:10107/31690 -- state:paused -- attr:AudioAttributes: usage=1 content=0 flags=0x200 tags= bundle=null
ID:15 -- type:android.media.SoundPool -- u/pid:1000/3719 -- state:idle -- attr:AudioAttributes: usage=13 content=4 flags=0x0 tags= bundle=null
```
And while VRV is open and playing:
```
ID:23 -- type:android.media.SoundPool …
```

Added VRV app play state detection and related audio state detection changes

---

androidtv/constants.py

```bash
#!/bin/bash
#SCREEN_ON="state=ON"
SCREEN_ON="state=OFF"
#AWAKE="Awake"
AWAKE="asleep"
#AUDIO_STATE="paused"
AUDIO_STATE="started"
#AUDIO_STATE=""
echo -e "\nCurrent CMD_ANDROIDTV_PROPERTIES_LAZY"
echo "$SCREEN_ON" | grep -q 'state=ON' && echo -e '1\c' && echo "$AWAKE" | grep -q "Awake" && echo -e '1\c' && echo "$AUDIO_STATE" | grep -q paused && echo -e '1\c' || (echo "$AUDIO_STATE" | grep -q "started" && echo -e '2\c' || echo -e '0\c')
echo
echo -e "\nUpdated CMD_ANDROIDTV_PROPERTIES_LAZY"
echo "$SCREEN_ON" | grep -q 'state=ON' && echo -e '1\c' && echo "$AWAKE" | grep -q "Awake" && echo -e '1\c' && (echo "$AUDIO_STATE" | grep -q paused && echo -e '1\c' || (echo "$AUDIO_STATE" | grep -q "started" && echo -e '2\c' || echo -e '0\c'))
echo
echo
```
```
Current …
```

Fix 'CMD_ANDROIDTV_PROPERTIES_*' commands

---

androidtv/androidtv.py
androidtv/basetv.py
tests/test_androidtv.py

While testing Plex, I found HA was reporting a `standby` state every 15-30 minutes before quickly correcting back to `playing`. This causes my lights to flash on and off which isn't ideal during a movie.
I'm using a 2017 Nvidia Shield device with the [`c6dbc683eb71676baf16ae6125226304d428b889`](https://github.com/JeffLIrion/ha-androidtv/tree/c6dbc683eb71676baf16ae6125226304d428b889) on `ha-androidtv/master`. But this has been going on for a few weeks now. I can't really pinpoint a date though..
I set up the logging to report the states of the Shield every 1 second and managed to capture some extra states that I would consider `playing`, but the code considers standby.
Here are some of those log line snippets. ('wake_lock_size' = `3`, `4`, `5`, and `7`)
All of those `wake_lock_size` were …

Change Plex `wake_lock_size` priority

---

androidtv/androidtv/base_androidtv.py
tests/test_androidtv_sync.py

These were the only states I found that were usable to map to the playing / paused state. #12 
If you need any more information I'm happy to help!

Map states from nl.nlziet app

---

androidtv/__init__.py
androidtv/adb_manager/adb_manager_async.py
androidtv/adb_manager/adb_manager_sync.py
androidtv/basetv/basetv_async.py
androidtv/basetv/basetv_sync.py
androidtv/constants.py
androidtv/setup_async.py

In most case during initial connection to my FireTV devices I receive back the error:
```
[androidtv.adb_manager.adb_manager_async] Couldn't connect to 192.168.10.18:5555.  TcpTimeoutException: Connecting to 192.168.10.18:5555 timed out (1.0 seconds)
```
With this PR it will be possible to increase a little bit the `transport_timeout` used in the `connect` method that is currently hard coded to 1 second.

Add transport_timeout_s parameter for setup and adb_connect methods

---

androidtv/constants.py
tests/test_constants.py

Parsing of current app is broken incase google assitant gets triggered and closed again. Suddenly we have Windows #1 as `mOwnerUid=10050 showForAllUsers=false package=com.google.android.inputmethod.latin appop=NONE` this is not correct.
In this pull request based on the link issue, I've moved the command to find the windows that has the inputfocus instead
See: https://github.com/home-assistant/core/issues/69723

Fix for current application in android 11

---

androidtv/constants.py
tests/test_constants.py

This implements the change mentioned in #323.
The original issue of not getting any information in HASS was caused by `update()`
https://github.com/JeffLIrion/python-androidtv/blob/b1425b1b0d1d826e25948fad15ca3650433e3d5d/androidtv/androidtv/androidtv_async.py#L84
using the lazy parameter in `get_properties()`, which doesn't retrieve any information unless the screen is on:
https://github.com/JeffLIrion/python-androidtv/blob/b1425b1b0d1d826e25948fad15ca3650433e3d5d/androidtv/androidtv/androidtv_async.py#L182
The change adds an additional way to check whether or not the screen is on, and should still function properly in older android versions.
More work is needed to determine the cause of periodic state:Off logs: https://github.com/JeffLIrion/python-androidtv/issues/323#issuecomment-128932 …

Fix CMD_SCREEN_ON constant in accordance with #323

---

androidtv/basetv/basetv_async.py
androidtv/basetv/basetv_sync.py
tests/async_patchers.py
tests/patchers.py
tests/test_basetv_async.py
tests/test_basetv_sync.py

On Nvidia Shield, power service can sometimes reply with "Failed to write while dumping service". When this happens, power state will be output as `None`, even when device is turned on. This can cause Home Assistant to randomly switch playing -> standby -> playing momentarily.
As a workaround, this PR attempts to detect the error and re-send the command when it happens.

Retry power command on error

---

androidtv/constants.py
tests/test_constants.py

I've noticed that my Nvidia Shield will sometimes completely omit `mInputMethodTarget` in the dumpsys window output. For example:
```
WINDOW MANAGER WINDOWS (dumpsys window windows)
Window #0 Window{5c08713 u0 org.xbmc.kodi/org.xbmc.kodi.Main}:
mDisplayId=0 rootTaskId=1290 mSession=Session{40887aa 10484:u0a10087} mClient=android.os.BinderProxy@4266202
mOwnerUid=10087 showForAllUsers=false package=org.xbmc.kodi appop=NONE
mAttrs={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION fmt=TRANSLUCENT wanim=0x1030001 preferredRefreshRate=60.000004 preferredDisplayMode=21 sysuil=true
fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED
pfl=FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
vsysui=HIDE_NAVIGATION FULLSCREEN LAYOUT_STABLE LAYOUT_HIDE_NAVIGATION …
```

also detect focused window by mInputMethodInputTarget

---

androidtv/constants.py

While working on a different feature, I noticed several of my regular apps were not mapped to friendly names, so adding them.

Adding HBO, Hulu, Peacock, and Paramount+

---

androidtv/constants.py
androidtv/firetv/base_firetv.py
tests/test_firetv_sync.py

- Adds support for the german TV Streaming App "RTL Plus" (formerly TVNOW)
- The wake_lock states were observed via the ADB console
- ✅  Passing
- ✅  Ready for Review

add support for RTL PLUS (formerly TVNOW)

---

.github/workflows/python-package.yml
androidtv/adb_manager/adb_manager_async.py
setup.py

`asyncio.wait_for` creates another tasks which leads to some race conditions in cancelation and a performance hit
cpython 3.12 will change the underlying implementation of `asyncio.wait_for` to use `asyncio.wait` but that is still a long way off for many people:
https://github.com/python/cpython/pull/98518
seen on profile courtesy of @Madelena

Switch usage of asyncio.wait_for to async_timeout

---

androidtv/basetv/basetv.py
androidtv/constants.py
tests/test_constants.py

Fixes [#102565](https://github.com/home-assistant/core/issues/102565) and [https://github.com/JeffLIrion/python-androidtv/issues/292](https://github.com/JeffLIrion/python-androidtv/issues/292) and updates [https://github.com/JeffLIrion/python-androidtv/commit/e8b09aab7931a65be7e9beb71409c079da172b43](https://github.com/JeffLIrion/python-androidtv/commit/e8b09aab7931a65be7e9beb71409c079da172b43)

Add -A option to ps command to list all Fire TV processes

---

androidtv/constants.py
tests/test_constants.py

Fix "Failed to write while dumping service window: Broken pipe"

---

androidtv/basetv/basetv.py
androidtv/constants.py
tests/test_constants.py

Only tested on the Google TV Streamer for now, so the HDMI input stuff may need further tweaking once this actually rolls out to things with HDMI inputs.

Add Android 14 support
